import type { Metadata } from "next";
// import { GeistSans } from "geist/font/sans";
import "./globals.css";
import BackButtonHandler from "./BackButtonHandler";
import UnifiedPermissionsGate from "./components/UnifiedPermissionsGate";
import SessionInterceptorInit from "./SessionInterceptorInit";

// const geistSans = GeistSans({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={"antialiased"}
      >
        <SessionInterceptorInit />
        <BackButtonHandler />
        <UnifiedPermissionsGate />
        {children}
      </body>
    </html>
  );
}
